### ISSUE TITLE
No module named 'advanced_scrapy_proxies'

### ISSUE THREAD

**Issue by Marow** [reanalytics-databoutique/advanced-scrapy-proxies#1]
I get that error:

`builtins.ModuleNotFoundError: No module named 'advanced_scrapy_proxies'`

And yes, i installed with pip install advanced_scrapy_proxies

With scrapy_proxies it works, but not with your advanced version. I get everytime error, whe start running the scrapy crawl.
Can you check please? I think there must be something wrong...

`Requirement already satisfied: advanced_scrapy_proxies in /usr/local/lib/python3.8/dist-packages (0.1.2)`
when i type in pip install again

**Comment by pigivinci** [comment]
There was a typo in the readme. 
The correct configuration is:

DOWNLOADER_MIDDLEWARES = {
      'scrapy.downloadermiddlewares.retry.RetryMiddleware': 90,
      'advanced-scrapy-proxies.RandomProxy': 100,
      'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 110
}
